# Generated by Django 5.2 on 2025-09-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraped_data', models.JSONField()),
                ('scrape_type', models.CharField(choices=[('product_list', 'Product List'), ('product_detail', 'Product Detail')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
