# Generated by Django 5.2 on 2025-07-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_brand_alter_product_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pharmacy',
            field=models.CharField(choices=[('apteka24', 'Apteka24')], default='apteka24', max_length=15),
            preserve_default=False,
        ),
    ]
