# Generated by Django 5.2 on 2025-08-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pharmacy',
            field=models.CharField(choices=[('apteka24', 'Apteka24'), ('annifarm', 'Annifarm')], max_length=15),
        ),
    ]
