# Generated by Django 5.2 on 2025-09-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
