# Generated by Django 5.2 on 2025-09-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desciption',
            field=models.TextField(blank=True),
        ),
    ]
