# Generated by Django 5.2 on 2025-09-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_external_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('external_id', 'pharmacy'), name='unique_eid_pharmacy'),
        ),
    ]
