# Generated by Django 5.2 on 2025-10-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_unique_eid_pharmacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=500, unique=True)),
                ('last_seen_at', models.DateTimeField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
