# Generated by Django 5.2 on 2025-10-04 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productdiscover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('catalog_base_url', models.URLField(unique=True)),
                ('catalog_max_pages', models.PositiveSmallIntegerField()),
                ('catalog_scraping_delay_in_seconds', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='productdiscover',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.pharmacy'),
        ),
    ]
