# Generated by Django 5.2 on 2025-10-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_pharmacy_productdiscover_pharmacy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductDeprecated',
        ),
    ]
