# Generated by Django 5.2 on 2025-10-14 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_brand_created_at_brand_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdiscover',
            name='product_last_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdiscover',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=400)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('is_in_stock', models.BooleanField()),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productdiscover',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
