# Generated by Django 5.2 on 2025-10-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_productdiscover_product_last_scraped_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='homepage',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacy-logos'),
        ),
    ]
