# Generated by Django 5.2 on 2025-10-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_pharmacy_homepage_pharmacy_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='homepage',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='logo',
            field=models.ImageField(upload_to='pharmacy-logos'),
        ),
    ]
