# Generated by Django 5.2 on 2025-10-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_pharmacy_homepage_alter_pharmacy_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDeprecated',
        ),
    ]
