# Generated by Django 5.2 on 2025-10-20 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_delete_productdeprecated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'verbose_name_plural': 'Pharmacies'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productdiscover',
            options={'verbose_name_plural': 'Product discoveries'},
        ),
    ]
