# Generated by Django 5.2 on 2025-10-24 15:53

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_discount_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='catalog_url_queryparams_string',
            field=models.CharField(blank=True, help_text="Enter query params starting with '?', e.g., '?key1=value1&key2=value2'", max_length=100, validators=[products.models.validate_catalog_queryparams_string]),
        ),
    ]
