# Generated by Django 5.2 on 2025-12-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_productcollection_productincollection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincollection',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='productincollection',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductCollection',
        ),
        migrations.DeleteModel(
            name='ProductInCollection',
        ),
    ]
