# Generated by Django 5.2 on 2025-12-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_remove_productincollection_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='can_the_product_be_updated_from_catagol',
            field=models.BooleanField(default=False),
        ),
    ]
