# Generated by Django 5.2 on 2025-12-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_pharmacy_can_the_product_be_updated_from_catagol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='can_the_product_be_updated_from_catagol',
            new_name='can_the_product_be_updated_from_catalog',
        ),
    ]
