# Generated by Django 5.2 on 2025-12-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_rename_can_the_product_be_updated_from_catagol_pharmacy_can_the_product_be_updated_from_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_in_stock',
        ),
    ]
