# Generated by Django 5.2 on 2026-01-24 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Health Tags',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=400)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand')),
            ],
            options={
                'verbose_name_plural': 'Product Groups',
            },
        ),
        migrations.CreateModel(
            name='ProductGroupHealthTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productgroup')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.healthtag')),
            ],
        ),
        migrations.AddField(
            model_name='productgroup',
            name='tags',
            field=models.ManyToManyField(through='products.ProductGroupHealthTag', to='products.healthtag'),
        ),
        migrations.CreateModel(
            name='ProductV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=400)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('url', models.URLField(max_length=600, unique=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productgroup')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.pharmacy')),
            ],
            options={
                'verbose_name_plural': 'Product V2',
            },
        ),
        migrations.AddConstraint(
            model_name='productgrouphealthtag',
            constraint=models.UniqueConstraint(fields=('tag', 'group'), name='unique_together_tag_group'),
        ),
    ]
