# Generated by Django 5.2 on 2026-01-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_healthtag_productgroup_productgrouphealthtag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='catalog_base_url',
            field=models.URLField(max_length=2048, unique=True),
        ),
    ]
