# Generated by Django 5.2 on 2026-01-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_pharmacy_catalog_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='catalog_base_url',
            field=models.CharField(max_length=2048, unique=True),
        ),
    ]
