# Generated by Django 5.2 on 2026-01-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_pharmacy_catalog_base_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='can_the_product_be_updated_from_catalog',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='catalog_scraping_delay_in_seconds',
        ),
    ]
