# Generated by Django 5.2 on 2026-02-02 18:41

import django.db.models.deletion
import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_remove_pharmacy_can_the_product_be_updated_from_catalog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url_without_page', models.CharField(max_length=2048, unique=True)),
                ('max_pages', models.PositiveSmallIntegerField()),
                ('page_numbering_starts_at_zero', models.BooleanField(default=False)),
                ('queryparams_string', models.CharField(blank=True, help_text="Enter query params starting with '?', e.g., '?key1=value1&key2=value2'", max_length=256, validators=[products.validators.validate_catalog_queryparams_string])),
                ('is_active', models.BooleanField(default=True)),
                ('short_description', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('pharmacy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.pharmacy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productv2')),
            ],
        ),
        migrations.AddField(
            model_name='productv2',
            name='categories',
            field=models.ManyToManyField(through='products.ProductCategory', to='products.category'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('product', 'category'), name='unique_together_product_category'),
        ),
    ]
