# Generated by Django 5.2 on 2026-02-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_category_pharmacycatalog_productcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productv2',
            name='dosage',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productv2',
            name='form_with_count',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
