# Generated by Django 5.2 on 2026-02-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_productv2_dosage_productv2_form_with_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productv2',
            name='is_reviewed',
            field=models.BooleanField(default=True),
        ),
    ]
