# Generated by Django 5.2 on 2026-02-05 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_productv2_is_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgrouphealthtag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='productgroup',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='productgrouphealthtag',
            name='group',
        ),
        migrations.DeleteModel(
            name='HealthTag',
        ),
        migrations.DeleteModel(
            name='ProductGroupHealthTag',
        ),
    ]
