# Generated by Django 5.2 on 2026-02-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_remove_productgrouphealthtag_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='catalog_base_url',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='catalog_max_pages',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='catalog_url_queryparams_string',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='logo',
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='homepage',
            field=models.URLField(unique=True),
        ),
    ]
