# Generated by Django 5.2 on 2026-02-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_remove_pharmacy_catalog_base_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdiscover',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productdiscover',
            name='pharmacy',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductDiscover',
        ),
    ]
