# Generated by Django 5.2 on 2026-02-12 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylists', '0001_initial'),
        ('products', '0041_remove_productdiscover_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductV2',
            new_name='Product',
        ),
    ]
