# Generated by Django 5.2 on 2026-02-12 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_rename_productv2_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
