# Generated by Django 5.2 on 2026-02-12 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
