# Generated by Django 5.2 on 2026-02-14 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='is_reviewed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='name',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.CreateModel(
            name='ProductGroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productgroup')),
            ],
        ),
        migrations.AddField(
            model_name='productgroup',
            name='categories',
            field=models.ManyToManyField(through='products.ProductGroupCategory', to='products.category'),
        ),
        migrations.AddConstraint(
            model_name='productgroupcategory',
            constraint=models.UniqueConstraint(fields=('group', 'category'), name='unique_together_group_category'),
        ),
    ]
