# Generated by Django 5.2 on 2026-02-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_productgroup_is_reviewed_alter_productgroup_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
