# Generated by Django 5.2 on 2026-02-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_product_normalized_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, max_length=400),
        ),
    ]
