# Generated by Django 5.2 on 2026-03-01 12:32

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0047_brand_normalized_name_alter_product_normalized_name"),
    ]

    operations = [
        TrigramExtension(),
    ]
