from environ import Env

env = Env()

APTEKA24_MAX_PAGES = env("APTEKA24_MAX_PAGES", int)
APTEKA24_DELAY_IN_SECONDS = env("APTEKA24_DELAY_IN_SECONDS", int)
APTEKA24_LIST_BASE_URL = env("APTEKA24_LIST_BASE_URL")


ANNIFARM_MAX_PAGES = env("ANNIFARM_MAX_PAGES", int)
ANNIFARM_DELAY_IN_SECONDS = env("ANNIFARM_DELAY_IN_SECONDS", int)
ANNIFARM_LIST_BASE_URL = env("ANNIFARM_LIST_BASE_URL")
