PRODUCT_CARD_SELECTOR = ".product-content"
PRODUCT_TITLE_SELECTOR = ".woocommerce-loop-product__title"
PRODUCT_PRICE_SELECTOR = ".price"
PRODUCT_BRAND_SELECTOR = ".yith-wcbr-brands"
PRODUCT_LINK_SELECTOR = ".woocommerce-LoopProduct-link.woocommerce-loop-product__link"
