# Generated by Django 5.2 on 2026-02-12 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0040_remove_pharmacy_catalog_base_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_added_through_smart_search', models.BooleanField(default=False)),
                ('mylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylists.mylist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productv2')),
            ],
        ),
        migrations.AddField(
            model_name='mylist',
            name='products',
            field=models.ManyToManyField(through='mylists.MyListItem', to='products.productv2'),
        ),
        migrations.AddConstraint(
            model_name='mylistitem',
            constraint=models.UniqueConstraint(fields=('product', 'mylist'), name='unique_together_product_mylist'),
        ),
        migrations.AddConstraint(
            model_name='mylist',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_together_name_user'),
        ),
    ]
