# Generated by Django 5.2 on 2025-12-04 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylists', '0001_initial'),
        ('products', '0026_productcollection_productincollection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mylist',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_together_name_user'),
        ),
    ]
